services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/[dep-dir]
      # for pnpm
      - /app/.pnpm-store
      - pnpm_store:/root/.local/share/pnpm/store
    ports:
      - [port]:[port]
    environment:
      # for pnpm
      - PNPM_HOME=/root/.local/share/pnpm
      - PNPM_CONFIG_STORE_DIR=/root/.local/share/pnpm/store
    command: [start-command]

volumes:
  [name]:
